import React, {useState,useEffect,useRef} from 'react';
import {ArrowRight,ArrowUpRight,ArrowUp,ArrowLeft,ArrowsOut,X,DiscordLogo,Check,Minus} from '@phosphor-icons/react';
import {motion,MotionConfig,useScroll,useMotionValueEvent,useReducedMotion} from 'motion/react';
import '@fontsource-variable/inter';
import art from './art-sources.json';
const discord='https://discord.gg/pM6tQah';
const projects={
 lrz:{name:'LRZ Bikeshop',type:'Identidade visual',source:'https://www.behance.net/gallery/228162769/LRZ-Bikeshop-Branding',credit:'Identidade visual: Guilherme Travaglini / Guit Design. Logotipo: Claus Veronesi / Design Ideal.',desc:'Performance, tecnologia e uma identidade com movimento.',crop:'lrz-cover'},
 umidifica:{name:'Umidifica',type:'Identidade visual',source:'https://www.behance.net/gallery/139211061/Umidifica-Apresentacao',credit:'Guit Design',desc:'Uma identidade leve, natural e reconhecível.',crop:'umidifica-cover'},
 codders:{name:'Codders',type:'Identidade visual',source:'https://www.behance.net/gallery/133800077/Codders-Apresentacao',credit:'Guit Design',desc:'Uma marca e suas aplicações, do símbolo aos detalhes.',crop:'codders-cover'},
 distric99:{name:'Distric99',type:'Identidade visual · GTA RP',source:'https://www.behance.net/gallery/239355943/VISUAL-IDENTITY-GTAV-ROLEPLAY-Cidade-Distric99',credit:'Projeto em colaboração: Guit Design, Mateus Rodri e Mateus Rodriguez. Créditos completos no Behance.',desc:'Uma identidade vibrante para um universo de histórias.',crop:'distric-cover'}
};
const homePieces=[{src:art.lrz[0],name:'LRZ · Aplicação do logotipo',crop:'lrz-detail'},{src:art.codders[0],name:'Codders · Papelaria',crop:'codders-detail'},{src:art.umidifica[3],name:'Umidifica · Aplicações'},{src:'/assets/guit-clouds.png',name:'Guit Design · Identidade'}];
const generalLogos=[{src:'/assets/void.png',name:'VØID'},{src:'/assets/vision.png',name:'VISION'},{src:'/assets/maiscode.png',name:'Mais+Code'},{src:'/assets/stories-que-engajam.png',name:'Stories que Engajam'},{src:'/assets/aquabeleza.png',name:'Aqua Beleza'}].map(item=>({...item,crop:'general-logo'}));
const animated=[{src:'/assets/brava.gif',name:'Cidade Brava · Logo animado'},{src:'/assets/foco.gif',name:'Foco · Logo animado'},{src:'/assets/just-survive.gif',name:'Just Survive · Logo animado'}];
const fivemLogos=[
 {src:'/assets/fivem-baixada-rj.png',name:'Baixada RJ',crop:'fivem-logo'},
 {src:'/assets/fivem-fox-west.png',name:'FOX West',crop:'fivem-logo'},
 {src:'/assets/fivem-revolution-rp.png',name:'Revolution RP',crop:'fivem-logo'},
 {src:'/assets/fivem-cidadela-customs.png',name:'Cidadela Customs',crop:'fivem-logo'}
];
const socialPieces=[
 {src:'/assets/fivez-social-1.png',name:'FiveZ Brasil · Gameplay antecipada'},
 {src:'/assets/fivez-social-2.png',name:'FiveZ Brasil · Evento de Halloween'},
 {src:'/assets/fivez-social-3.png',name:'FiveZ Brasil · Encerramento de temporada'}
];
const vipIcons=[
 {src:'/assets/fivez-vip-1.png',name:'FiveZ Brasil · Acesso beta padrão'},
 {src:'/assets/fivez-vip-2.png',name:'FiveZ Brasil · Acesso beta farmador'}
];
function Logo(){return <a href='/' className='brand' aria-label='Guit Design — início'><span className='logo-window'><img src='/assets/guit-logo-v8-cropped.png' alt=''/></span><img className='brand-wordmark' src='/assets/guit-inkbleed.png' alt='Guit'/></a>}
function CTA({children='Conversar no Discord'}){return <a className='cta' href={discord} target='_blank' rel='noreferrer'><DiscordLogo weight='fill' size={23}/><span>{children}</span><ArrowUpRight className="arrow-up-right" size={19}/></a>}
function Picture({src,alt,crop='',eager=false}){return <div className={`picture ${crop}`}><img src={src} alt={alt} loading={eager?'eager':'lazy'} decoding='async'/></div>}
function Header({fivem=false}){
 const isHome=window.location.pathname==='/';
 const [scrolled,setScrolled]=useState(()=>window.scrollY>72);
 const {scrollY}=useScroll();const reduced=useReducedMotion();
 useMotionValueEvent(scrollY,'change',latest=>setScrolled(latest>72));
 return <div className='header-slot'><motion.header className={`topbar ${fivem?'topbar-fivem':''} ${scrolled?'is-scrolled':''}`} initial={false} animate={{y:scrolled&&!reduced?-2:0}} transition={{duration:reduced?0:.25,ease:'easeOut'}}><Logo/><nav aria-label='Navegação principal'><a href='/' aria-current={isHome?'page':undefined}>Estúdio</a><a href={fivem?'/fivem#projetos':'/#projetos'}>Projetos</a><a href='/fivem' aria-current={fivem?'page':undefined}><span className={!fivem?'shiny-text':''}>FiveM</span></a>{fivem&&<a href='/fivem#planos'>Planos</a>}</nav><a className='nav-contact' aria-label='Conversar no Discord' href={discord} target='_blank' rel='noreferrer'><DiscordLogo size={20} weight='fill'/><span>Vamos conversar</span><ArrowUpRight className="arrow-up-right" size={17}/></a></motion.header></div>
}
function Reveal({as='div',children,...props}){const reduced=useReducedMotion();const Tag=as==='button'?motion.button:as==='article'?motion.article:motion.div;return <Tag initial={reduced?false:{opacity:0,y:14}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.08}} transition={{duration:reduced?0:.5,ease:[.22,1,.36,1]}} {...props}>{children}</Tag>}
function Heading({title,children}){if(!title&&!children)return null;return <Reveal className='section-heading'><div><h2>{title}</h2></div>{children}</Reveal>}
function Contact({fivem=false}){return <section className='contact' id='contato'><div className='contact-copy'><h2>{fivem?<>Sua cidade.<br/>Sua identidade.</>:<>Vamos criar<br/>algo seu?</>}</h2><CTA/><a className='text-link' href={fivem?'/':'/fivem'}>{fivem?'Conheça o estúdio':'Design para FiveM'}<ArrowRight className="arrow-right"/></a></div><img src='/assets/contact-clouds.png' alt='Símbolo rosa da Guit Design entre nuvens' loading='lazy'/></section>}
function Footer(){return <footer><Logo/><div><a href='https://www.behance.net/guitdesign' target='_blank' rel='noreferrer'>Behance<ArrowUpRight className="arrow-up-right" size={13}/></a><a href={discord} target='_blank' rel='noreferrer'>Discord<ArrowUpRight className="arrow-up-right" size={13}/></a><a href='https://linktr.ee/guitdesign' target='_blank' rel='noreferrer'>Linktree<ArrowUpRight className="arrow-up-right" size={13}/></a></div><small>© {new Date().getFullYear()} Guit Design</small></footer>}
function Gallery({items,title='Social Media.',onOpen,three=false}){return <section className='section'><Heading title={title}/><div className={`gallery ${three?'three':''}`}>{items.map((item,i)=><Reveal as='button' className='piece' key={item.src} onClick={()=>onOpen(items,i)} aria-label={`Ampliar ${item.name}`}><Picture {...item} alt={item.name}/><span className='piece-caption'>{item.name}<span className='circle'><ArrowsOut size={18}/></span></span></Reveal>)}</div></section>}
function Lightbox({data,onClose}){
 const [index,setIndex]=useState(data.index);const [zoom,setZoom]=useState(false);const dialog=useRef(null);const imageArea=useRef(null);const item=data.items[index];
 useEffect(()=>{const previous=document.activeElement;dialog.current.showModal();document.body.style.overflow='hidden';return()=>{document.body.style.overflow='';previous?.focus()}},[]);
 function move(d){setZoom(false);setIndex(i=>(i+d+data.items.length)%data.items.length);imageArea.current?.scrollTo(0,0)}
 return <dialog ref={dialog} className='lightbox' onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}} onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();move(1)}if(e.key==='ArrowLeft'){e.preventDefault();move(-1)}}} aria-label={item.name}><div className='lightbox-bar'><span>{item.name}</span><div className='lightbox-actions'><button className='zoom-toggle' onClick={()=>{setZoom(v=>!v);imageArea.current?.scrollTo(0,0)}} aria-pressed={zoom}>{zoom?'Ajustar':'Ver detalhes'}<ArrowsOut size={18}/></button><button onClick={onClose} aria-label='Fechar galeria'><X size={25}/></button></div></div><div ref={imageArea} className={`lightbox-image ${zoom?'is-zoomed':''}`}><img key={item.src} src={item.src} alt={item.name}/></div><div className='lightbox-controls'><button onClick={()=>move(-1)} aria-label='Imagem anterior'><ArrowLeft className="arrow-left" size={24}/></button><span aria-live='polite'>{index+1} / {data.items.length}</span><button onClick={()=>move(1)} aria-label='Próxima imagem'><ArrowRight className="arrow-right" size={24}/></button></div></dialog>
}
function Home({onOpen}){const [slide,setSlide]=useState(0);useEffect(()=>{const timer=setTimeout(()=>setSlide(value=>(value+1)%3),5000);return ()=>clearTimeout(timer)},[slide]);const [expanded,setExpanded]=useState(false);const keys=['lrz','umidifica','codders'];const key=keys[slide],p=projects[key];return <><div className='home-opening'><Header/><div className='intro'><p className='eyebrow'>ESTÚDIO DE DESIGN GRÁFICO</p><h1>Design com<br/>presença.</h1><CTA/></div><div className='hero-project'><motion.div key={key} className='hero-slide' initial={{opacity:0}} animate={{opacity:1}} transition={{duration:.4}}><a href={`/projetos/${key}`} className='hero-art' aria-label={`Ver projeto ${p.name}`}><Picture src={art[key][0]} alt={`Identidade visual ${p.name}`} crop={p.crop} eager/></a><div className='hero-caption'><div><h2>{p.name}</h2><a href={`/projetos/${key}`} className='project-link'><span className='circle'><ArrowRight className="arrow-right"/></span>Ver projeto</a></div><div className='slide-tabs' aria-label='Projetos em destaque'>{keys.map((k,i)=><button key={k} aria-label={`Mostrar ${projects[k].name}`} aria-pressed={i===slide} onClick={()=>setSlide(i)}>0{i+1}</button>)}</div></div></motion.div></div></div><main id='conteudo'><section className='section' id='projetos'><Heading eyebrow='PROJETOS QUE IMPORTAM' title='Projetos.'><button className='text-link' aria-expanded={expanded} aria-controls='more-projects' onClick={()=>setExpanded(!expanded)}>{expanded?'Ver menos':'Ver todos'}{expanded?<Minus/>:<ArrowRight className="arrow-right"/>}</button></Heading><a href='/projetos/umidifica' className='featured-project'><Picture src={art.umidifica[0]} alt='Umidifica — identidade visual' crop='umidifica-cover'/></a><div className='project-meta'><span>Umidifica <span className='muted'>— Identidade visual</span></span><a href='/projetos/umidifica'>Ver projeto<span className='circle'><ArrowRight className="arrow-right"/></span></a></div>{expanded&&<div className='additional-projects' id='more-projects'>{['lrz','codders'].map(k=><a href={`/projetos/${k}`} key={k}><Picture src={art[k][0]} alt={projects[k].name} crop={projects[k].crop}/><div className='project-meta'>{projects[k].name}<ArrowUpRight className="arrow-up-right"/></div></a>)}</div>}</section><div id='logotipos' className='general-logos'><Gallery items={generalLogos} title='Logotipos.' eyebrow='MARCAS COM PERSONALIDADE' onOpen={onOpen} three/></div><Gallery items={homePieces.slice(0,2)} onOpen={onOpen}/><Contact/></main><Footer/></>}
const common=['Logotipo','Logo animado em GIF','Banner de conectando animado','Banner detail animado'];
const plans=[{name:'Essentials',price:237,desc:'A identidade para começar.',items:common},{name:'Signature',price:374,desc:'Sua identidade em movimento.',items:[...common,'Loadscreen animada em MP4']},{name:'Elite',price:667,desc:'Uma presença completa.',items:[...common,'Loadscreen animada em MP4','Topo do Discord animado','15 peças para loja VIP']}];
function Plans(){return <section className='section plans-section' id='planos'><Heading title='Planos.'/><div className='plans'>{plans.map((p,index)=><Reveal as='article' className={`plan plan-${p.name.toLowerCase()}`} key={p.name}><div className='plan-level' aria-hidden='true'>{[0,1,2].map(level=><span key={level} className={level<=index?'lit':''}/>)}</div><h3>{p.name}</h3><p className='price'><span>R$</span>{p.price}</p><ul>{p.items.map(it=><li key={it}><Check size={17}/>{it}</li>)}</ul><CTA>Quero o {p.name}</CTA></Reveal>)}</div><div className='plan-notes'><p>Loadscreen: MP4 · 1920 × 1080 · cerca de 30s.</p></div><aside className='plan-addon' aria-label='Adicional opcional de banners Mastodon'><div className='addon-art' aria-hidden='true'><span/><span/><span/></div><div className='addon-copy'><span className='addon-label'>ADICIONAL OPCIONAL</span><h3>Banners Mastodon</h3><p>3 banners do perfil do servidor</p></div><strong className='addon-price'>+R$87</strong><a className='addon-action' href={discord} target='_blank' rel='noreferrer'>Quero adicionar<ArrowUpRight className="arrow-up-right" size={18}/></a></aside></section>}
function FiveM({onOpen}){const [tab,setTab]=useState('social');return <div className='fivem-page'><div className='fivem-opening'><Header fivem/><img className='sunset' src='/assets/fivem-car-hero.png' alt='Ilustração de carro esportivo roxo sob um céu violeta'/><div className='fivem-intro'><p className='eyebrow'>GUIT DESIGN / FIVEM</p><h1>Uma identidade.<br/>Infinitas histórias.</h1><div className='hero-actions'><CTA/><a href='#projetos' className='text-link'>Ver projetos<ArrowRight className="arrow-right"/></a></div></div><div className='fivem-bottom'><span>LOGOTIPOS · BANNERS · ANIMAÇÕES</span><a href='#planos'>Planos <ArrowRight className="arrow-right"/></a></div></div><main id='conteudo'><section className='section' id='projetos'><Heading eyebrow='UNIVERSOS COM PERSONALIDADE' title='Projetos.'/><a href='/projetos/distric99' className='district-feature'><Picture src={art.distric99[0]} alt='Distric99 — projeto de identidade visual'/></a><div className='project-meta'><span>Distric99 <span className='muted'>— Identidade visual completa</span></span><a href='/projetos/distric99'>Ver projeto<span className='circle'><ArrowRight className="arrow-right"/></span></a></div></section><section className='section showcase'><Heading eyebrow='FEITO PARA SER VISTO' title='Galeria.'/><div className='filter-tabs' role='group' aria-label='Tipo de trabalho'><button aria-pressed={tab==='social'} onClick={()=>setTab('social')}>Social media</button><button aria-pressed={tab==='logofolio'} onClick={()=>setTab('logofolio')}>Logotipos</button><button aria-pressed={tab==='logos'} onClick={()=>setTab('logos')}>Logotipos animados</button><button aria-pressed={tab==='vip'} onClick={()=>setTab('vip')}>Ícones Loja VIP</button></div>{tab==='social'?<Gallery items={socialPieces} title='' eyebrow='' onOpen={onOpen} three/>:tab==='logofolio'?<div className='fivem-logo-gallery'><Gallery items={fivemLogos} title='' eyebrow='' onOpen={onOpen} three/><a className='text-link' href='https://www.behance.net/gallery/185950411/LOGOFOLIO-2023-FiveM-Servers-Others' target='_blank' rel='noreferrer'>Ver coletânea no Behance<ArrowUpRight className="arrow-up-right"/></a></div>:tab==='logos'?<Gallery items={animated} title='' eyebrow='' onOpen={onOpen} three/>:<Gallery items={vipIcons} title='' eyebrow='' onOpen={onOpen} three/>}</section><Plans/><Contact fivem/></main><Footer/></div>}
function Project({id,onOpen}){const p=projects[id];if(!p)return <><Header/><main className='section not-found'><h1>Projeto não encontrado.</h1><a href='/' className='text-link'>Voltar ao estúdio<ArrowLeft className="arrow-left"/></a></main><Footer/></>;const fivem=id==='distric99';return <><Header fivem={fivem}/><main id='conteudo' className='project-page'><div className='project-heading'><a href={fivem?'/fivem#projetos':'/#projetos'} className='text-link'><ArrowLeft className="arrow-left"/>Voltar aos projetos</a><p className='eyebrow'>{p.type}</p><h1>{p.name}</h1><p className='credits'>{p.credit}</p></div><div className='project-images'>{art[id].map((src,i)=><button key={src} onClick={()=>onOpen(art[id].map((s,j)=>({src:s,name:`${p.name} · ${j+1}`})),i)} aria-label={`Ampliar ${p.name}, imagem ${i+1}`}><img src={src} alt={`${p.name} — apresentação ${i+1}`} loading={i?'lazy':'eager'}/></button>)}</div><div className='project-end'><a href={p.source} target='_blank' rel='noreferrer' className='text-link'>Projeto e créditos no Behance<ArrowUpRight className="arrow-up-right"/></a><CTA/></div><Contact fivem={fivem}/></main><Footer/></>}
function BackToTop(){const [visible,setVisible]=useState(false);const [footerLift,setFooterLift]=useState(0);useEffect(()=>{const update=()=>{setVisible(window.scrollY>400);const footer=document.querySelector('footer');const footerTop=footer?.getBoundingClientRect().top??window.innerHeight;setFooterLift(footerTop<window.innerHeight?window.innerHeight-footerTop+16:0)};update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);return()=>{window.removeEventListener('scroll',update);window.removeEventListener('resize',update)}},[]);return visible?<button className='back-to-top' style={{'--footer-lift':`${footerLift}px`}} aria-label='Voltar ao topo' title='Voltar ao topo' onClick={()=>window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}><ArrowUp size={19}/><span>Voltar ao topo</span></button>:null}
export function App(){const [lightbox,setLightbox]=useState(null);const path=window.location.pathname.replace(/\/$/,'')||'/';const id=path.split('/')[2];useEffect(()=>{document.title=path==='/fivem'?'Design para FiveM — Guit Design':path.startsWith('/projetos/')?`${projects[id]?.name||'Projeto'} — Guit Design`:'Guit Design — Design com presença';},[path,id]);useEffect(()=>{if(window.location.hash){requestAnimationFrame(()=>document.getElementById(window.location.hash.slice(1))?.scrollIntoView({behavior:'instant'}));}},[path]);const onOpen=(items,index)=>setLightbox({items,index});return <MotionConfig reducedMotion='user'><a className='skip' href='#conteudo'>Pular para o conteúdo</a>{path==='/fivem'?<FiveM onOpen={onOpen}/>:path.startsWith('/projetos/')?<Project id={id} onOpen={onOpen}/>:<Home onOpen={onOpen}/ >}{!lightbox&&<BackToTop/>}{lightbox&&<Lightbox data={lightbox} onClose={()=>setLightbox(null)}/>}</MotionConfig>}



