import React, {createContext,useContext,useState,useEffect,useRef} from 'react';
import {ArrowRight,ArrowUpRight,ArrowUp,ArrowLeft,ArrowsOut,CaretDown,X,DiscordLogo,Check,Minus,Star} from '@phosphor-icons/react';
import {motion,AnimatePresence,MotionConfig,useScroll,useMotionValueEvent,useReducedMotion,useTransform} from 'motion/react';
import '@fontsource-variable/inter';
import art from './art-sources.json';
import {getTranslation,translations} from './i18n';
const discord='https://discord.gg/pM6tQah';
const LanguageContext=createContext(null);
const useLanguage=()=>useContext(LanguageContext);
const projects={
 lrz:{name:'LRZ Bikeshop',type:'Identidade visual',source:'https://www.behance.net/gallery/228162769/LRZ-Bikeshop-Branding',credit:'Identidade visual: Guilherme Travaglini / Guit Design. Logotipo: Claus Veronesi / Design Ideal.',desc:'Performance, tecnologia e uma identidade com movimento.',crop:'lrz-cover'},
 umidifica:{name:'Umidifica',type:'Identidade visual',source:'https://www.behance.net/gallery/139211061/Umidifica-Apresentacao',credit:'Guit Design',desc:'Uma identidade leve, natural e reconhecível.',crop:'umidifica-cover'},
 codders:{name:'Codders',type:'Identidade visual',source:'https://www.behance.net/gallery/133800077/Codders-Apresentacao',credit:'Guit Design',desc:'Uma marca e suas aplicações, do símbolo aos detalhes.',crop:'codders-cover'},
 district99:{name:'District99',type:'Identidade visual · GTA RP',source:'https://www.behance.net/gallery/239355943/VISUAL-IDENTITY-GTAV-ROLEPLAY-Cidade-Distric99',credit:'Projeto em colaboração: Guit Design, Mateus Rodri e Mateus Rodriguez. Créditos completos no Behance.',desc:'Uma identidade vibrante para um universo de histórias.',crop:'distric-cover'}
};
const homePieces=['Nuuvmed · Automação','Nuuvmed · Boas-vindas','Tocatambor · Sarau','Tocatambor · Matrículas','Sabor do Norte · Milky Moo','Sabor do Norte · Novos sabores','iSafeCell · Primeiro iPhone','iSafeCell · Modelos de iPhone'].map((name,i)=>({src:'/assets/studio-social-'+(i+1)+'.png',name,crop:'studio-social'}));
const generalLogos=[{src:'/assets/void.png',name:'VØID'},{src:'/assets/vision.png',name:'VISION'},{src:'/assets/troll-ai.png',name:'TROLL.AI'},{src:'/assets/stories-que-engajam.png',name:'Stories que Engajam'},{src:'/assets/aquabeleza.png',name:'Aqua Beleza'}].map(item=>({...item,crop:'general-logo'}));
const animated=[{src:'/assets/brava.gif',name:'Cidade Brava · Logo animado'},{src:'/assets/foco.gif',name:'Foco · Logo animado'},{src:'/assets/just-survive.gif',name:'Just Survive · Logo animado'}];
const fivemLogos=[
 {src:'/assets/fivem-baixada-rj.png',name:'Baixada RJ',crop:'fivem-logo'},
 {src:'/assets/fivem-fox-west.png',name:'FOX West',crop:'fivem-logo'},
 {src:'/assets/fivem-revolution-rp.png',name:'Revolution RP',crop:'fivem-logo'},
 {src:'/assets/fivem-cidadela-customs.png',name:'Cidadela Customs',crop:'fivem-logo'}
];
const socialPieces=[
 {src:'/assets/fivez-social-1.png',name:'FiveZ Brasil · Gameplay antecipada'},
 {src:'/assets/fivez-social-2.png',name:'FiveZ Brasil · Evento de Halloween'},
 {src:'/assets/fivez-social-3.png',name:'FiveZ Brasil · Encerramento de temporada'}
];
const vipIcons=[
 {src:'/assets/fivez-vip-1.png',name:'FiveZ Brasil · Acesso beta padrão'},
 {src:'/assets/fivez-vip-2.png',name:'FiveZ Brasil · Acesso beta farmador'},
 {src:'/assets/vip-personagem-extra.png',name:'Riverside · Personagem extra'},
 {src:'/assets/vip-acesso-antecipado.png',name:'Riverside · Acesso antecipado'},
 {src:'/assets/vip-reset-aparencia.png',name:'Exodus · Reset appearance'},
 {src:'/assets/vip-extra-char-slot.png',name:'Exodus · Extra character slot'}
];
function RotatingWord(){
 const {t,language}=useLanguage();const words=t('words');
 const [index,setIndex]=useState(0);const reduced=useReducedMotion();
 useEffect(()=>setIndex(0),[language]);useEffect(()=>{if(reduced)return;const timer=setInterval(()=>setIndex(i=>(i+1)%words.length),4000);return()=>clearInterval(timer)},[reduced,language,words.length]);
 return <span className='rotating-word' aria-label={words[index]}><AnimatePresence mode='wait' initial={false}><motion.span key={`${language}-${index}`} className='roulette-word brand-emphasis' aria-hidden='true' initial='enter' animate='show' exit='leave' variants={{enter:{},show:{transition:{staggerChildren:.025}},leave:{transition:{staggerChildren:.018}}}}>{[...words[index]].map((letter,i)=><motion.span className='roulette-letter' key={i} variants={{enter:{y:'115%'},show:{y:0},leave:{y:'-115%'}}} transition={{duration:.18,ease:'easeInOut'}}>{letter}</motion.span>)}</motion.span></AnimatePresence></span>
}
function Logo(){const {t}=useLanguage();return <a href='/' className='brand' aria-label={`Guit Design — ${t('studio')}`}><span className='logo-window'><img src='/assets/guit-logo-v10-cropped.png' alt=''/></span></a>}
function CTA({children}){const {t}=useLanguage();return <a className='cta' href={discord} target='_blank' rel='noreferrer'><DiscordLogo weight='fill' size={23}/><span>{children||t('talkDiscord')}</span><ArrowUpRight className="arrow-up-right" size={19}/></a>}
function Picture({src,alt,crop='',eager=false}){return <div className={`picture ${crop}`}><img src={src} alt={alt} loading={eager?'eager':'lazy'} decoding='async'/></div>}
function LanguageMenu(){const {language,setLanguage,t}=useLanguage();const ref=useRef(null);return <details className='language-menu' ref={ref}><summary aria-label={`${t('language')}: ${translations[language].localeName}`}><span>{language.toUpperCase()}</span><CaretDown size={12}/></summary><div className='language-options' role='menu' aria-label={t('language')}>{['pt','es','en'].map(code=><button type='button' role='menuitemradio' aria-checked={language===code} key={code} onClick={()=>{setLanguage(code);ref.current?.removeAttribute('open')}}><span>{code.toUpperCase()}</span><small>{translations[code].localeName}</small></button>)}</div></details>}
function Header({fivem=false}){
 const {t}=useLanguage();
 const isHome=window.location.pathname==='/';
 const [scrolled,setScrolled]=useState(()=>window.scrollY>72);
 const {scrollY}=useScroll();const reduced=useReducedMotion();
 useMotionValueEvent(scrollY,'change',latest=>setScrolled(latest>72));
 return <div className='header-slot'><motion.header layout className={`topbar ${fivem?'topbar-fivem':''} ${scrolled?'is-scrolled':''}`} initial={false} animate={{y:scrolled&&!reduced?-2:0}} transition={{duration:reduced?0:.2,ease:'easeInOut'}}><Logo/><nav aria-label={t('navLabel')}><a href='/' aria-current={isHome?'page':undefined}>{t('studio')}</a><a href={fivem?'/fivem#projetos':'/#projetos'}>{t('projects')}</a><a href='/fivem' aria-current={fivem?'page':undefined}><span className={!fivem?'shiny-text':''}>FiveM</span></a>{fivem&&<a href='/fivem#planos'>{t('plans')}</a>}</nav><div className='topbar-actions'><LanguageMenu/><a className='nav-contact' aria-label={t('talkDiscord')} href={discord} target='_blank' rel='noreferrer'><DiscordLogo size={20} weight='fill'/><span>{t('talk')}</span><ArrowUpRight className="arrow-up-right" size={17}/></a></div></motion.header></div>
}
function Reveal({as='div',children,...props}){const reduced=useReducedMotion();const Tag=as==='button'?motion.button:as==='article'?motion.article:motion.div;return <Tag initial={reduced?false:{opacity:0,y:14}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.08}} transition={{duration:reduced?0:.5,ease:[.22,1,.36,1]}} {...props}>{children}</Tag>}
function ParallaxStars(){const {scrollYProgress}=useScroll();const reduced=useReducedMotion();const yA=useTransform(scrollYProgress,[0,1],reduced?[0,0]:[180,-420]);const yB=useTransform(scrollYProgress,[0,1],reduced?[0,0]:[253,-483]);const yC=useTransform(scrollYProgress,[0,1],reduced?[0,0]:[85,-515]);const rotateA=useTransform(scrollYProgress,[0,1],reduced?[0,0]:[-18,175]);const rotateB=useTransform(scrollYProgress,[0,1],reduced?[0,0]:[28,-155]);return <div className='parallax-stars' aria-hidden='true'><motion.img className='parallax-star parallax-star-c' src='/assets/guit-star-red.svg' style={{y:yC,rotate:rotateB}}/><motion.img className='parallax-star parallax-star-a' src='/assets/guit-star-red.svg' style={{y:yA,rotate:rotateA}}/><motion.img className='parallax-star parallax-star-b' src='/assets/guit-star-red.svg' style={{y:yB,rotate:rotateB}}/></div>}
function BrandStars(){return <span className='brand-stars' aria-hidden='true'>{[0,1,2].map(i=><Star key={i} weight='fill'/>)}</span>}
function Heading({title,children}){if(!title&&!children)return null;return <Reveal className='section-heading'><div className='branded-heading'><BrandStars/><h2>{title}</h2></div>{children}</Reveal>}
function Contact({fivem=false}){const {t}=useLanguage();const copy=fivem?t('contactFiveM'):t('contactHome');return <section className='contact' id='contato'><div className='contact-copy'><BrandStars/><h2>{copy[0]}<br/>{copy[1]}</h2><CTA/><a className='text-link' href={fivem?'/':'/fivem'}>{fivem?t('discoverStudio'):t('designForFiveM')}<ArrowRight className="arrow-right"/></a></div><div className='contact-visual' role='img' aria-label={t('contactVisual')}/></section>}
function Footer(){return <footer><Logo/><div><a href='https://www.behance.net/guitdesign' target='_blank' rel='noreferrer'>Behance<ArrowUpRight className="arrow-up-right" size={13}/></a><a href={discord} target='_blank' rel='noreferrer'>Discord<ArrowUpRight className="arrow-up-right" size={13}/></a><a href='https://linktr.ee/guitdesign' target='_blank' rel='noreferrer'>Linktree<ArrowUpRight className="arrow-up-right" size={13}/></a></div><small>© {new Date().getFullYear()} Guit Design</small></footer>}
function Gallery({items,title,onOpen,three=false}){const {t}=useLanguage();return <section className='section'><Heading title={title===undefined?t('socialMedia'):title}/><div className={`gallery ${three?'three':''}`}>{items.map((item,i)=><Reveal as='button' className='piece' key={item.src} onClick={()=>onOpen(items,i)} aria-label={`${t('enlarge')} ${item.name}`}><Picture {...item} alt={item.name}/><span className='piece-caption'>{item.name}<span className='circle'><ArrowsOut size={18}/></span></span></Reveal>)}</div></section>}
function Lightbox({data,onClose}){
 const {t}=useLanguage();const [index,setIndex]=useState(data.index);const [zoom,setZoom]=useState(false);const dialog=useRef(null);const imageArea=useRef(null);const item=data.items[index];
 useEffect(()=>{const previous=document.activeElement;dialog.current.showModal();document.body.style.overflow='hidden';return()=>{document.body.style.overflow='';previous?.focus()}},[]);
 function move(d){setZoom(false);setIndex(i=>(i+d+data.items.length)%data.items.length);imageArea.current?.scrollTo(0,0)}
 return <dialog ref={dialog} className='lightbox' onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}} onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();move(1)}if(e.key==='ArrowLeft'){e.preventDefault();move(-1)}}} aria-label={item.name}><div className='lightbox-bar'><span>{item.name}</span><div className='lightbox-actions'><button className='zoom-toggle' onClick={()=>{setZoom(v=>!v);imageArea.current?.scrollTo(0,0)}} aria-pressed={zoom}>{zoom?t('fit'):t('details')}<ArrowsOut size={18}/></button><button onClick={onClose} aria-label={t('closeGallery')}><X size={25}/></button></div></div><div ref={imageArea} className={`lightbox-image ${zoom?'is-zoomed':''}`}><img key={item.src} src={item.src} alt={item.name}/></div><div className='lightbox-controls'><button onClick={()=>move(-1)} aria-label={t('previousImage')}><ArrowLeft className="arrow-left" size={24}/></button><span aria-live='polite'>{index+1} / {data.items.length}</span><button onClick={()=>move(1)} aria-label={t('nextImage')}><ArrowRight className="arrow-right" size={24}/></button></div></dialog>
}
function Home({onOpen}){const {t}=useLanguage();const [slide,setSlide]=useState(0);useEffect(()=>{const timer=setTimeout(()=>setSlide(value=>(value+1)%3),10000);return ()=>clearTimeout(timer)},[slide]);const [expanded,setExpanded]=useState(false);const keys=['codders','lrz','umidifica'];const key=keys[slide],p=projects[key];const localizedHome=homePieces.map((item,i)=>({...item,name:t('captions.home')[i]}));return <><div className='home-opening'><Header/><div className='intro'><p className='eyebrow'>{t('homeEyebrow')}</p><h1>{t('designWith')}<br/><RotatingWord/>.</h1><div className='studio-hero-actions'><CTA/><a className='cta cta-instagram' href='https://www.instagram.com/oguitdesign/' target='_blank' rel='noreferrer'>{t('talkInstagram')}<ArrowUpRight className='arrow-up-right' size={19}/></a></div></div><div className='hero-project'><motion.div key={key} className='hero-slide' initial={{opacity:0}} animate={{opacity:1}} transition={{duration:.4}}><a href={`/projetos/${key}`} className='hero-art' aria-label={`${t('viewProject')} ${p.name}`}><Picture src={art[key][0]} alt={`${t('visualIdentity')} ${p.name}`} crop={p.crop} eager/></a><div className='hero-caption'><div><h2>{p.name}</h2><a href={`/projetos/${key}`} className='project-link'><span className='circle'><ArrowRight className="arrow-right"/></span>{t('viewProject')}</a></div><div className='slide-tabs' aria-label={t('featuredProjects')}>{keys.map((k,i)=><button key={k} aria-label={`${t('show')} ${projects[k].name}`} aria-pressed={i===slide} onClick={()=>setSlide(i)}>0{i+1}</button>)}</div></div></motion.div></div></div><main id='conteudo'><ParallaxStars/><section className='section' id='projetos'><Heading title={`${t('projects')}.`}><button className='text-link' aria-expanded={expanded} aria-controls='more-projects' onClick={()=>setExpanded(!expanded)}>{expanded?t('fewerProjects'):t('allProjects')}{expanded?<Minus/>:<ArrowRight className="arrow-right"/>}</button></Heading><a href='/projetos/umidifica' className='featured-project'><Picture src={art.umidifica[0]} alt={`Umidifica — ${t('visualIdentity')}`} crop='umidifica-cover'/></a><div className='project-meta'><span>Umidifica <span className='muted'>— {t('visualIdentity')}</span></span><a href='/projetos/umidifica'>{t('viewProject')}<span className='circle'><ArrowRight className="arrow-right"/></span></a></div>{expanded&&<div className='additional-projects' id='more-projects'>{['lrz','codders'].map(k=><a href={`/projetos/${k}`} key={k}><Picture src={art[k][0]} alt={projects[k].name} crop={projects[k].crop}/><div className='project-meta'>{projects[k].name}<ArrowUpRight className="arrow-up-right"/></div></a>)}</div>}</section><div id='logotipos' className='general-logos'><Gallery items={generalLogos} title={t('logos')} onOpen={onOpen} three/></div><div className="studio-social-gallery"><Gallery items={localizedHome} onOpen={onOpen} three/></div><Contact/></main><Footer/></>}
const common=['Logotipo','Logo animado em GIF','Banner de conectando animado','Banner detail animado'];
const plans=[{name:'Essentials',price:237,desc:'A identidade para começar.',items:common},{name:'Signature',price:374,desc:'Sua identidade em movimento.',items:[...common,'Loadscreen animada em MP4']},{name:'Elite',price:667,desc:'Uma presença completa.',items:[...common,'Loadscreen animada em MP4','Topo do Discord animado','15 peças para loja VIP']}];
function Plans(){const {t}=useLanguage();const base=t('planItems');const localized=[{name:'Essentials',price:237,items:base},{name:'Signature',price:374,items:[...base,t('loadscreen')]},{name:'Elite',price:667,items:[...base,t('loadscreen'),t('discordHeader'),t('vipPieces')]}];return <section className='section plans-section' id='planos'><Heading title={t('planTitle')}/><div className='plans'>{localized.map((p,index)=><Reveal as='article' className={`plan plan-${p.name.toLowerCase()}`} key={p.name}><div className='plan-level' aria-hidden='true'>{[0,1,2].map(level=><span key={level} className={level<=index?'lit':''}/>)}</div><h3>{p.name}</h3><p className='price'><span>R$</span>{p.price}</p><ul>{p.items.map(it=><li key={it}><Check size={17}/>{it}</li>)}</ul><CTA>{t('want')} {p.name}</CTA></Reveal>)}</div><div className='plan-notes'><p>{t('loadscreenNote')}</p></div><aside className='plan-addon' aria-label={t('mastodonAria')}><div className='addon-art' aria-hidden='true'><span/><span/><span/></div><div className='addon-copy'><span className='addon-label'>{t('optionalAddon')}</span><h3>Banners Mastodon</h3><p>{t('mastodonCopy')}</p></div><strong className='addon-price'>+R$87</strong><a className='addon-action' href={discord} target='_blank' rel='noreferrer'>{t('add')}<ArrowUpRight className="arrow-up-right" size={18}/></a></aside></section>}
function FiveM({onOpen}){const {t}=useLanguage();const [tab,setTab]=useState('social');const hero=t('fiveMHero');const localizedSocial=socialPieces.map((item,i)=>({...item,name:t('captions.social')[i]}));const localizedAnimated=animated.map((item,i)=>({...item,name:t('captions.animated')[i]}));const localizedVip=vipIcons.map((item,i)=>({...item,name:t('captions.vip')[i]}));return <div className='fivem-page'><div className='fivem-opening'><Header fivem/><img className='sunset' src='/assets/fivem-car-hero.png' alt={t('fiveMAlt')}/><div className='fivem-intro'><p className='eyebrow'>GUIT DESIGN / FIVEM</p><h1>{hero[0]}<br/>{hero[1]}<br/><span className='brand-emphasis'>{hero[2]}</span></h1><div className='hero-actions'><CTA/><a href='#projetos' className='text-link'>{t('allProjects')}<ArrowRight className="arrow-right"/></a></div></div><div className='fivem-bottom'><span>{t('fiveMServices')}</span><a href='#planos'>{t('plans')} <ArrowRight className="arrow-right"/></a></div></div><main id='conteudo'><ParallaxStars/><section className='section' id='projetos'><Heading eyebrow='UNIVERSOS COM PERSONALIDADE' title={`${t('projects')}.`}/><a href='/projetos/district99' className='district-feature'><Picture src={art.district99[0]} alt={`District99 — ${t('visualIdentity')}`}/></a><div className='project-meta'><span>District99 <span className='muted'>— {t('completeIdentity')}</span></span><a href='/projetos/district99'>{t('viewProject')}<span className='circle'><ArrowRight className="arrow-right"/></span></a></div></section><section className='section showcase'><Heading eyebrow='FEITO PARA SER VISTO' title={t('gallery')}/><div className='filter-tabs' role='group' aria-label={t('workType')}><button aria-pressed={tab==='social'} onClick={()=>setTab('social')}>{t('social')}</button><button aria-pressed={tab==='logofolio'} onClick={()=>setTab('logofolio')}>{t('logos').replace('.','')}</button><button aria-pressed={tab==='logos'} onClick={()=>setTab('logos')}>{t('animatedLogos')}</button><button aria-pressed={tab==='vip'} onClick={()=>setTab('vip')}>{t('vipIcons')}</button></div>{tab==='social'?<Gallery items={localizedSocial} title='' eyebrow='' onOpen={onOpen} three/>:tab==='logofolio'?<div className='fivem-logo-gallery'><Gallery items={fivemLogos} title='' eyebrow='' onOpen={onOpen} three/><a className='text-link' href='https://www.behance.net/gallery/185950411/LOGOFOLIO-2023-FiveM-Servers-Others' target='_blank' rel='noreferrer'>{t('viewCollection')}<ArrowUpRight className="arrow-up-right"/></a></div>:tab==='logos'?<Gallery items={localizedAnimated} title='' eyebrow='' onOpen={onOpen} three/>:<Gallery items={localizedVip} title='' eyebrow='' onOpen={onOpen} three/>}</section><Plans/><Contact fivem/></main><Footer/></div>}
function Project({id,onOpen}){const {t}=useLanguage();const p=projects[id];if(!p)return <><Header/><main className='section not-found'><h1>{t('projectNotFound')}</h1><a href='/' className='text-link'>{t('backStudio')}<ArrowLeft className="arrow-left"/></a></main><Footer/></>;const fivem=id==='district99';return <><Header fivem={fivem}/><main id='conteudo' className='project-page'><div className='project-heading'><a href={fivem?'/fivem#projetos':'/#projetos'} className='text-link'><ArrowLeft className="arrow-left"/>{t('backProjects')}</a><p className='eyebrow'>{id==='district99'?`${t('visualIdentity')} · GTA RP`:t('visualIdentity')}</p><h1>{p.name}</h1><p className='credits'>{t(`credits.${id}`)}</p></div><div className='project-images'>{art[id].map((src,i)=><button key={src} onClick={()=>onOpen(art[id].map((s,j)=>({src:s,name:`${p.name} · ${j+1}`})),i)} aria-label={`${t('enlarge')} ${p.name}, ${t('presentation')} ${i+1}`}><img src={src} alt={`${p.name} — ${t('presentation')} ${i+1}`} loading={i?'lazy':'eager'}/></button>)}</div><div className='project-end'><a href={p.source} target='_blank' rel='noreferrer' className='text-link'>{t('projectCredits')}<ArrowUpRight className="arrow-up-right"/></a><CTA/></div><Contact fivem={fivem}/></main><Footer/></>}
function BackToTop(){const {t}=useLanguage();const [visible,setVisible]=useState(false);const [footerLift,setFooterLift]=useState(0);useEffect(()=>{const update=()=>{setVisible(window.scrollY>400);const footer=document.querySelector('footer');const footerTop=footer?.getBoundingClientRect().top??window.innerHeight;setFooterLift(footerTop<window.innerHeight?window.innerHeight-footerTop+16:0)};update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);return()=>{window.removeEventListener('scroll',update);window.removeEventListener('resize',update)}},[]);return visible?<button className='back-to-top' style={{'--footer-lift':`${footerLift}px`}} aria-label={t('backTop')} title={t('backTop')} onClick={()=>window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}><ArrowUp size={19}/><span>{t('backTop')}</span></button>:null}
export function App(){const [language,setLanguage]=useState(()=>{const saved=localStorage.getItem('guit-language');return ['pt','es','en'].includes(saved)?saved:'pt'});const t=key=>getTranslation(language,key);const [lightbox,setLightbox]=useState(null);const path=window.location.pathname.replace(/\/$/,'')||'/';const routeId=path.split('/')[2];const id=routeId==='distric99'?'district99':routeId;useEffect(()=>{localStorage.setItem('guit-language',language);document.documentElement.lang=language==='pt'?'pt-BR':language;document.title=path==='/fivem'?t('documentFiveM'):path.startsWith('/projetos/')?`${projects[id]?.name||t('documentProject')} — Guit Design`:t('documentHome')},[path,id,language]);useEffect(()=>{if(window.location.hash){requestAnimationFrame(()=>document.getElementById(window.location.hash.slice(1))?.scrollIntoView({behavior:'instant'}));}},[path]);const onOpen=(items,index)=>setLightbox({items,index});return <LanguageContext.Provider value={{language,setLanguage,t}}><MotionConfig reducedMotion='user'><a className='skip' href='#conteudo'>{t('skip')}</a>{path==='/fivem'?<FiveM onOpen={onOpen}/>:path.startsWith('/projetos/')?<Project id={id} onOpen={onOpen}/>:<Home onOpen={onOpen}/ >}{!lightbox&&<BackToTop/>}{lightbox&&<Lightbox data={lightbox} onClose={()=>setLightbox(null)}/>}</MotionConfig></LanguageContext.Provider>}



